name: 'create-json'
author: 'jsdaniell'
description: 'Create an JSON file from secret or a string of a json.'
inputs:
  name:
    description: 'The name of the file to be written. | file.json '
    required: true
  json:
    description: 'The json string that can be a secret of the github repo or a string of a json. | "{"title": "my json"}" '
    required: true
  dir:
    description: 'Optional subfolder directory to save the json file. | src/ '
    required: false
outputs:
  successfully:
    description: 'Feedback message of success '
runs:
  using: "node20"
  main: "./dist/index.js"
branding:
  icon: 'file-text'
  color: 'purple'